package strings;
/*
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */
public class FindTheDifference {

    // 6/24/2022 solution
    public char findTheDifference(String s, String t) {
        int[] sArr = new int[26];
        int[] tArr = new int[26];

        for (int i = 0; i < s.length(); i++) {
            sArr[s.charAt(i) - 'a']++;
        }

        for (int i = 0; i < t.length(); i++) {
            tArr[t.charAt(i) - 'a']++;
        }

        for (int i = 0; i < sArr.length; i++) {
            if (sArr[i] != tArr[i]) {
                int n = i + 97;
                return (char)n;
            }
        }

        return ' ';
    }

    // Top solution was to add all the ascii values of both strings and find the difference. The difference will be the char
    public char findTheDifference(String s, String t) {
        int[] sArr = new int[26];
        int[] tArr = new int[26];

        for (int i = 0; i < s.length(); i++) {
            sArr[s.charAt(i) - 'a']++;
            tArr[t.charAt(i) - 'a']++;
        }

        tArr[t.charAt(t.length() - 1) - 'a']++; // Getting the last char in t since its length is 1 greater than s

        int diff = 97; // The ascii value of 'a'

        for (int i = 0; i < tArr.length; i++) {
            if (sArr[i] != tArr[i]) {
                diff += i;
            }
        }

        return (char)diff;
    }
}
